INSERT INTO participante (nombre, edad, coche, titulos) VALUES
('Manuel Senra', 63, 'Peugeot 306 Maxi', 5),
('Alexis Vieitez', 35, 'Fórmula Outeda', 4),
('Jacobo Senín', 40, 'Barqueta Nova Proto', 1),
('Pablo Rey', 38, 'Fórmula SMB X21', 2),
('Jorge Pérez Alonso', 42, 'BMW M3 E92 GT4, Citroën DS3 R5', 0),
('José Pose', 55, 'Renault 5 GT Turbo', 1),
('José L. Santos', 60, 'Lola BMW, Osella BMW', 3),
('José R. Fernández', 58, 'Ralt RT-30, Martini MK-39', 2),
('José M. Martínez', 50, 'Mitsubishi Lancer Evo VI', 1),
('José A. Gómez', 48, 'Martini MK-34', 4),
('Iñigo Martínez', 45, 'Martini MK-42', 1),
('Benito Varela', 47, 'Outeda Racing, Dicode RFC, Dicode FR', 3),
('Cristóbal Serantes', 44, 'Fórmula Ralt RT 34', 1),
('José Antonio Iglesias', 49, 'Mitsubishi Lancer Evo VIII', 2),
('Santiago Abad', 46, 'Audi A4 ST, Audi A4 STW', 3),
('César Rodríguez', 43, 'T. Castor TC3-C', 1),
('Jacobo Sobral', 39, 'Silver Car S2', 2),
('Miguel Ángel García', 41, 'Opel Astra TC06', 1),
('Monchu', 57, 'Ralt RT-30, Martini MK-39, Mitsubishi Lancer Evo VI', 3),
('Nonito', 56, 'Martini MK-34, Fórmula Hyupersa', 5),
('Toño Varela', 52, 'Osella BMW', 2),
('Víctor Abraham', 60, 'Dallara 384', 1),
('Alberto G. Camba', 62, 'Selex ST-4', 2),
('José Pose García', 55, 'Renault 5 GT Turbo', 1),
('José Luis Santos', 60, 'Lola BMW, Osella BMW', 3),
('Adrián Rodríguez', 37, 'Norma M20 FC', 1),
('Iván Suárez', 42, 'Silver Car S3', 2),
('Marcos Varela', 45, 'Osella PA21', 1),
('Rubén González', 39, 'Mitsubishi Lancer Evo IX', 0),
('David Castro', 41, 'Peugeot 106 S16', 0),
('Fernando López', 38, 'Norma M20 FC', 1),
('Álvaro Pérez', 36, 'BMW M3 E46', 0),
('Sergio Fernández', 40, 'Audi TT RS', 1),
('Óscar Martínez', 43, 'Ford Fiesta R5', 0),
('Andrés Gómez', 44, 'Subaru Impreza WRX', 1),
('Javier Domínguez', 39, 'Porsche 911 GT3', 2),
('Luis García', 37, 'Seat León Cup Racer', 0),
('Raúl Sánchez', 41, 'Citroën Saxo VTS', 0),
('Enrique Torres', 42, 'Norma M20 FC', 1),
('Daniel Méndez', 38, 'Peugeot 205 Rallye', 0),
('Alejandro Prieto', 36, 'Renault Clio Sport', 0),
('Iván López', 40, 'Mitsubishi Lancer Evo X', 1),
('Roberto Álvarez', 39, 'Ford Escort Cosworth', 1),
('Miguel Ángel Pérez', 42, 'BMW 320 ST', 0),
('Cristian Núñez', 37, 'Citroën C2 R2', 0),
('Andrés Vázquez', 38, 'Norma M20 FC', 1),
('Javier López', 41, 'Silver Car S3', 2),
('Marcos Fernández', 44, 'Osella PA21', 1),
('Rubén Castro', 39, 'Mitsubishi Lancer Evo IX', 0),
('David Suárez', 42, 'Peugeot 106 S16', 0),
('Fernando González', 37, 'Norma M20 FC', 1),
('Álvaro Domínguez', 36, 'BMW M3 E46', 0),
('Sergio Pérez', 40, 'Audi TT RS', 1),
('Óscar Torres', 43, 'Ford Fiesta R5', 0),
('Andrés Martínez', 44, 'Subaru Impreza WRX', 1),
('Javier Gómez', 39, 'Porsche 911 GT3', 2),
('Luis Domínguez', 37, 'Seat León Cup Racer', 0),
('Raúl Fernández', 41, 'Citroën Saxo VTS', 0),
('Enrique Méndez', 42, 'Norma M20 FC', 1),
('Daniel Torres', 38, 'Peugeot 205 Rallye', 0),
('Alejandro Suárez', 36, 'Renault Clio Sport', 0),
('Iván Prieto', 40, 'Mitsubishi Lancer Evo X', 1),
('Roberto Núñez', 39, 'Ford Escort Cosworth', 1),
('Miguel Ángel Torres', 42, 'BMW 320 ST', 0),
('Cristian Méndez', 37, 'Citroën C2 R2', 0),
('Adrián Vázquez', 39, 'Norma M20 FC', 1),
('Iván Torres', 41, 'Silver Car S3', 2),
('Marcos Suárez', 44, 'Osella PA21', 1),
('Rubén Fernández', 38, 'Mitsubishi Lancer Evo IX', 0),
('David López', 42, 'Peugeot 106 S16', 0),
('Fernando Prieto', 37, 'Norma M20 FC', 1),
('Álvaro Méndez', 36, 'BMW M3 E46', 0),
('Sergio Núñez', 40, 'Audi TT RS', 1),
('Óscar Pérez', 43, 'Ford Fiesta R5', 0),
('Andrés García', 44, 'Subaru Impreza WRX', 1),
('Javier Álvarez', 39, 'Porsche 911 GT3', 2),
('Luis Torres', 37, 'Seat León Cup Racer', 0),
('Raúl Domínguez', 41, 'Citroën Saxo VTS', 0),
('Enrique Suárez', 42, 'Norma M20 FC', 1),
('Daniel Fernández', 38, 'Peugeot 205 Rallye', 0),
('Alejandro López', 36, 'Renault Clio Sport', 0),
('Iván Méndez', 40, 'Mitsubishi Lancer Evo X', 1),
('Roberto Prieto', 39, 'Ford Escort Cosworth', 1),
('Miguel Ángel Núñez', 42, 'BMW 320 ST', 0),
('Cristian Pérez', 37, 'Citroën C2 R2', 0);